---
name: Image-Magick-Text-AutoBreak
version: 0.01
author:
  - 'Sugama Keita <sugama@jamadam.com>'
abstract: Utility for auto line break
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Encode: 0
  Image::Magick: 0
  Test::More: 0
provides:
  Image::Magick::Text::AutoBreak:
    file: lib/Image/Magick/Text/AutoBreak.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
